name: Simple Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v3

  deploy-dev:

    name: Deploy Dev
    runs-on: ubuntu-latest
    
    environment:
      name: dev
      
    needs: build
    steps:
      - name: Test
        run: echo "Hello World"
